
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: testDB
        ports:
            - 27017:27017
        volumes:
            - ./init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    rabbitmq:
        image: 'rabbitmq:3-management'
        environment:
            RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
            RABBITMQ_DEFAULT_USER: 'rabbitmq'
            RABBITMQ_DEFAULT_PASS: 'rabbitmq'
            RABBITMQ_DEFULT_HOST: '/'
        expose:
            - 5672
            - 15672
        healthcheck:
            test: [ "CMD", "nc", "-z", "localhost", "5672" ]
            interval: 5s
            timeout: 15s
            retries: 1
        ports:
            - '15672:15672'
            - '5672:5672'
